### PR TITLE
Send API to store

### PR DESCRIPTION
**Pull request by estherhayward**
Reason for this PR:
Connect api data with redux store. Still work in progress.

Why? 
Best pratice

### CODE REVIEW

**Review by AkashChandra92 — APPROVED** [review]
Forward!

**Review by future-ruins — APPROVED** [review]
LGTM

**Review by future-ruins — DISMISSED** [review]
Can we revert to old version with local state?

**Comment by future-ruins** [comment]
yes yes i want to go back in time

**Pull request closed without merging**
